namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: wini123456/techtrends
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits: 
    memory: 256Mi
    cpu: 500m

containerPort: 3111
livenessProbePath: /healthz
readinessProbePath: /healthz
